name: Task Reviewer Agent

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'A prompt to give the agent'
        required: false
        type: string
      issue_id:
        description: 'Issue ID for task to implement'
        required: true
        type: string
      project_overview_file:
        description: 'Path to the project overview markdown file'
        required: false
        type: string
        default: '.project/project-overview.md'
      execution_mode:
        description: 'Execution mode for the agent'
        required: true
        type: choice
        options:
          - Initialize
          - Continue

jobs:
  task-reviewer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write  # Required for OIDC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Read task reviewer script
        id: task-reviewer-agent-script
        run: |
          echo "system_prompt<<EOF" >> $GITHUB_OUTPUT
          cat .github/agent-scripts/task-reviewer.script.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "task<<EOF" >> $GITHUB_OUTPUT
          echo "project_overview:" >> $GITHUB_OUTPUT
          echo '```markdown' >> $GITHUB_OUTPUT
          cat ${{ inputs.project_overview_file }} >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "issue_number: ${{ inputs.issue_id }}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "Review the feature in issue #${{ inputs.issue_id }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - uses: Unshure/strands-action@main
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          system_prompt: ${{ steps.task-reviewer-agent-script.outputs.system_prompt }}
          session_id: ${{ inputs.issue_id || github.run_id }}
          session_s3_bucket: "ncclegg-typescript-session-test"
          tools: "editor,file_read,shell,http_request,list_pull_requests,list_issues,add_comment,create_issue,get_issue,get_pull_request,update_pull_request,get_pr_reviews,update_issue,get_issue_comments,notebook"
          # Prompt always overrides the task prompt for any mode
          # If the mode is "Initialize", then the prompt should provide the input parameters to the script
          # If the mode is "Continue", then the prompt should tell the agent to review the feedback on the issue.
          task: ${{ inputs.prompt || (inputs.execution_mode == 'Continue' && 'Review the feedback and continue.') || steps.task-reviewer-agent-script.outputs.task }}